config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :home
  resources :tables
  resources :menu_grid
  resources :menu_list
  resources :about_us
  resources :galary
  resources :events
  resources :blogs
  resources :blog_galary
  resources :blog_details
  resources :contact_us
  get 'admin/', to: 'admin/admin_home#index'
  namespace :admin do
    resources :admin_home
    resources :tables
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/table.rb
class Table < ApplicationRecord
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController

  def index

  end
end

app/controllers/admin/admin_home_controller.rb
class Admin::AdminHomeController < AdminController

  def index
  end
end

app/controllers/admin/tables_controller.rb
class Admin::TablesController < AdminController

  def index
    @tables = Table.all.order(:id)
  end

  def show
    @table = Table.find(params[:id])
  end

  def edit
    @table = Table.find(params[:id])
  end

  def update
    @table = Table.find(params[:id])
    @table.update(permit_params)
    redirect_to :back
  end

  def destroy
  end

  private
    def permit_params
      params.require(:table).permit(:table_code, :table_name, :description, :content)
    end
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base

  layout 'admin_application'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_details_controller.rb
class BlogDetailsController < ApplicationController

  def index

  end
end

app/controllers/blog_galary_controller.rb
class BlogGalaryController < ApplicationController

  def index

  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index

  end
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController

  def index

  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index

  end
end

app/controllers/galary_controller.rb
class GalaryController < ApplicationController

  def index

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
end

app/controllers/menu_grid_controller.rb
class MenuGridController < ApplicationController

  def index

  end
end

app/controllers/menu_list_controller.rb
class MenuListController < ApplicationController

  def index

  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about_us/index.html.slim
#preloader
  .loader.absolute-center
    .loader__box
      b.top
    .loader__box
      b.top
    .loader__box
      b.top
/! ================ Frist hader Area =================
.first_header
  .container
    .row
      .col-md-4
        .header_contact_details
          a href="#"
            i.fa.fa-phone
            | +1 (168) 314 5016
          a href="#"
            i.fa.fa-envelope-o
            | +1 (168) 314 5016
      .col-md-4
        .event_btn_inner
          a.event_btn href="table.html"
            i.fa.fa-table aria-hidden="true"
            | Book a Table
          a.event_btn href="event.html"
            i.fa.fa-calendar aria-hidden="true"
            | Book an Event
      .col-md-4
        .header_social
          ul
            li
              a href="#"
                i.fa.fa-facebook
            li
              a href="#"
                i.fa.fa-twitter
            li
              a href="#"
                i.fa.fa-linkedin
            li
              a href="#"
                i.fa.fa-rss
/! ================End Footer Area =================
/! ================End Footer Area =================
= render partial: "layouts/head_menu"
/! ================End Footer Area =================
/! ================Banner Area =================
section.banner_area
  .container
    .banner_content
      h4 About Us
      a href="#"  Home
      a.active href="#"  About Us
/! ================End Banner Area =================
/! ================About Us Content Area =================
section.about_us_content
  .container
    .row.about_inner_item
      .col-md-6
        .about_left_content
          h4 Since 1962
          p Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typeting, remaining essentially unchanged.
          ul
            li
              a href="#"
                i.fa.fa-arrow-circle-right aria-hidden="true"
                | Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            li
              a href="#"
                i.fa.fa-arrow-circle-right aria-hidden="true"
                | The standard chunk of Lorem Ipsum used.
            li
              a href="#"
                i.fa.fa-arrow-circle-right aria-hidden="true"
                | Sed ut perspiciatis unde omnis iste natus error.
            li
              a href="#"
                i.fa.fa-arrow-circle-right aria-hidden="true"
                | At vero eos et accusamus et iusto odio dignissimos.
      .col-md-6
        .about_right_image
          img alt="" src="img/about-item/about-item-1.jpg" /
      .col-md-12
        .about_single_content
          p There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sture there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.
    .row.about_inner_item
      .col-md-6
        .about_right_image
          img alt="" src="img/about-item/about-item-2.jpg" /
      .col-md-6
        .about_left_content
          h4 About Our Menu
          p Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typeting, remaining essentially unchanged.
          ul
            li
              a href="#"
                i.fa.fa-arrow-circle-right aria-hidden="true"
                | Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            li
              a href="#"
                i.fa.fa-arrow-circle-right aria-hidden="true"
                | The standard chunk of Lorem Ipsum used.
            li
              a href="#"
                i.fa.fa-arrow-circle-right aria-hidden="true"
                | Sed ut perspiciatis unde omnis iste natus error.
            li
              a href="#"
                i.fa.fa-arrow-circle-right aria-hidden="true"
                | At vero eos et accusamus et iusto odio dignissimos.
      .col-md-12
        .about_single_content
          p There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sture there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.
    .row.about_inner_item
      .col-md-6
        .about_left_content
          h4 Best Services
          p Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typeting, remaining essentially unchanged.
          ul
            li
              a href="#"
                i.fa.fa-arrow-circle-right aria-hidden="true"
                | Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            li
              a href="#"
                i.fa.fa-arrow-circle-right aria-hidden="true"
                | The standard chunk of Lorem Ipsum used.
            li
              a href="#"
                i.fa.fa-arrow-circle-right aria-hidden="true"
                | Sed ut perspiciatis unde omnis iste natus error.
            li
              a href="#"
                i.fa.fa-arrow-circle-right aria-hidden="true"
                | At vero eos et accusamus et iusto odio dignissimos.
      .col-md-6
        .about_right_image
          img alt="" src="img/about-item/about-item-3.jpg" /
      .col-md-12
        .about_single_content
          p There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sture there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.
/! ================End About Us Content Area =================
/! ================End Recent Blog Area =================
footer.footer_area
  .footer_widget_area
    .container
      .row
        .col-md-3
          aside.f_widget.about_widget
            .f_w_title
              h4 ABOUT RedCayenne
            p Lorem ipsum dolor sit amet, consectur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris ut.
            ul
              li
                a href="#"
                  i.fa.fa-facebook
              li
                a href="#"
                  i.fa.fa-twitter
              li
                a href="#"
                  i.fa.fa-google-plus
              li
                a href="#"
                  i.fa.fa-linkedin
        .col-md-3
          aside.f_widget.contact_widget
            .f_w_title
              h4 CONTACT US
            p Have questions, comments or just want to say hello:
            ul
              li
                a href="#"
                  i.fa.fa-envelope
                  | backpiper.com@gmail.com
              li
                a href="#"
                  i.fa.fa-phone
                  | +88 01911 854 378
              li
                a href="#"
                  i.fa.fa-map-marker
                  | 5001 E. Colorado Blvd. Suite 820,
                  br/
                  | Pasadena, CA 91106
        .col-md-3
          aside.f_widget.twitter_widget
            .f_w_title
              h4 Twitter Feed
            ul
              li
                a href="#"  @_sumonrahman:
                | Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat.
              li
                a href="#"  @_sumonrahman:
                | Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat.
        .col-md-3
          aside.f_widget.gallery_widget
            .f_w_title
              h4 Gallery On Flickr
            ul
              li
                a href="#"
                  img alt="" src="img/gallery/f-w-gallery/f-w-gallery-1.jpg" /
                  i.fa.fa-search
              li
                a href="#"
                  img alt="" src="img/gallery/f-w-gallery/f-w-gallery-2.jpg" /
                  i.fa.fa-search
              li
                a href="#"
                  img alt="" src="img/gallery/f-w-gallery/f-w-gallery-3.jpg" /
                  i.fa.fa-search
              li
                a href="#"
                  img alt="" src="img/gallery/f-w-gallery/f-w-gallery-4.jpg" /
                  i.fa.fa-search
              li
                a href="#"
                  img alt="" src="img/gallery/f-w-gallery/f-w-gallery-5.jpg" /
                  i.fa.fa-search
              li
                a href="#"
                  img alt="" src="img/gallery/f-w-gallery/f-w-gallery-6.jpg" /
                  i.fa.fa-search
  .copy_right_area
    .container
      .pull-left
        h5
        p
          /! Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0.
          | Copyright ©
          javascript:
            document.write(new Date().getFullYear());
          | All rights reserved | This template is made with
          i.fa.fa-heart-o aria-hidden="true"
          | by
          a href="https://colorlib.com" target="_blank"  Colorlib
          /! Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0.
      .pull-right
        ul.nav.navbar-nav.navbar-right
          li
            a href="#"  Home
          li.active
            a href="#"  About Us
          li
            a href="#"  Menu
          li
            a href="#"  Gallery
          li
            a href="#"  Reservation
          li
            a href="#"  News
          li
            a href="#"  Contact Us
/! ================End Recent Blog Area =================
/! jQuery (necessary for Bootstrap's JavaScript plugins)
script src="js/jquery-2.1.4.min.js"
/! Include all compiled plugins (below), or include individual files as needed
script src="js/bootstrap.min.js"
/! Extra plugin js
script src="vendors/bootstrap-selector/bootstrap-select.js"
script src="vendors/bootatrap-date-time/bootstrap-datetimepicker.min.js"
script src="vendors/owl-carousel/owl.carousel.min.js"
script src="vendors/isotope/imagesloaded.pkgd.min.js"
script src="vendors/isotope/isotope.pkgd.min.js"
script src="vendors/countdown/jquery.countdown.js"
script src="vendors/js-calender/zabuto_calendar.min.js"
/! gmaps Js
/! <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script
/! <script src="js/gmaps.min.js"></script
/! <script src="js/video_player.js"></script
script src="js/theme.js"

app/views/admin/admin_home/index.html.slim
.main-inner
  .container
    .row
      .span12
        .widget
          .widget-header
            span
            h3 ABC
          .widget-content

app/views/admin/tables/edit.html.slim
.main-inner
  .container
    .row
      .span12
        .widget
          .widget-header
            span
            h3 Table Management
          .widget-content
            = form_for @table, url: admin_table_path(@table), html: {class: "form-horizontal", method: :put} do |f|
              fieldset
                .control-group
                  label.control-label for="table_code"
                    | Table code
                  .controls
                    = f.text_field :table_code, class: "span6"
                .control-group
                  label.control-label for="table_name"
                    | Table name
                  .controls
                    = f.text_field :table_name, class: "span6"
                .control-group
                  label.control-label for="table_name"
                    | Description
                  .controls
                    = f.text_field :description, class: "span6"
                .control-group
                  label.control-label for="content"
                    | Content
                  .controls
                    = f.cktext_area :content, class: "span6"
                .form-actions
                  = f.submit "Save", class: "btn btn-primary"
                  = link_to "Cancel", admin_tables_path, class: "btn"

app/views/admin/tables/index.html.slim
.main-inner
  .container
    .row
      .span12
        .widget
          .widget-header
            span
            h3 Table Management
          .widget-content
            table.table.table-striped.table-bordered.action-table
              thead
                tr
                  th Table code
                  th Table name
                  th.td-actions style="width: 140px"
              tbody
                - @tables.each do |table|
                  tr
                    td
                      = table.table_code
                    td
                      = table.table_name
                    td.td-actions
                      = link_to "Edit", edit_admin_table_path(table), class: "btn btn-small btn-success"
                      = link_to "Detail", admin_table_path(table), class: "btn btn-small btn-success"
                      = link_to admin_table_path(table), class: "btn btn-danger btn-small", method: :delete do
                        i.btn-icon-only.icon-remove

app/views/admin/tables/show.html.slim
.main-inner
  .container
    .row
      .span12
        .widget
          .widget-header
            span
            h3 Table Management
          .widget-content
            form.form-horizontal
              fieldset
                .control-group
                  label.control-label for="table_code"
                    | Table code
                  .controls
                    span
                      = @table.table_code
                .control-group
                  label.control-label for="table_name"
                    | Table name
                  .controls
                    span
                      = @table.table_name
                .control-group
                  label.control-label for="table_name"
                    | Description
                  .controls
                    span
                      = @table.description
                .control-group
                  label.control-label for="content"
                    | Content
                  .controls
                    .accordion
                      .accordion-group
                        .accordion-heading
                        .accordion-body.collapse.in
                          .accordion-inner
                            = raw @table.content
                .form-actions
                  = link_to "Cancel", admin_tables_path, class: "btn"

app/views/contact_us/index.html.slim
#preloader
  .loader.absolute-center
    .loader__box
      b.top
    .loader__box
      b.top
    .loader__box
      b.top
/! ================ Frist hader Area =================
.first_header
  .container
    .row
      .col-md-4
        .header_contact_details
          a href="#"
            i.fa.fa-phone
            | +1 (168) 314 5016
          a href="#"
            i.fa.fa-envelope-o
            | +1 (168) 314 5016
      .col-md-4
        .event_btn_inner
          a.event_btn href="table.html"
            i.fa.fa-table aria-hidden="true"
            | Book a Table
          a.event_btn href="event.html"
            i.fa.fa-calendar aria-hidden="true"
            | Book an Event
      .col-md-4
        .header_social
          ul
            li
              a href="#"
                i.fa.fa-facebook
            li
              a href="#"
                i.fa.fa-twitter
            li
              a href="#"
                i.fa.fa-linkedin
            li
              a href="#"
                i.fa.fa-rss
/! ================End Footer Area =================
/! ================End Footer Area =================
= render partial: "layouts/head_menu"
/! ================End Footer Area =================
/! ================Banner Area =================
section.banner_area
  .container
    .banner_content
      h4 Contact Us
      a href="#"  Home
      a.active href="blog-gallery.html"  Contat Us
/! ================End Banner Area =================
/! ================Contact Area =================
section.contact_area
  .container
    .row
      .col-md-6
        .contact_details
          h3.contact_title Contact Info
          p There are many variations of passages of Lorem Ipsum available, but the majori have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a pas of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.
          p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
          .media
            .media-left
              i.fa.fa-map-marker
            .media-body
              h4 Addtress
              h5 Freedom Way, Jersey Ctity, NJ 07305, USA
          .media
            .media-left
              i.fa.fa-phone
            .media-body
              h4 Phone
              h5 +88 01911 854 378
          .media
            .media-left
              i.fa.fa-envelope-o
            .media-body
              h4 Email
              h5 backpiper.com@gmail.com
      .col-md-6
        .row.contact_form_area
          h3.contact_title Send Message
          form#contactForm action="contact_process.php" method="post"
            .form-group.col-md-12
              input#name.form-control name="name" placeholder=("First Name*") type="text" /
            .form-group.col-md-12
              input#last.form-control name="last" placeholder=("Last Name*") type="text" /
            .form-group.col-md-12
              input#email.form-control name="email" placeholder=("Your Email*") type="email" /
            .form-group.col-md-12
              input#subject.form-control name="subject" placeholder="Subject" type="text" /
            .form-group.col-md-12
              textarea#message.form-control name="message" placeholder=("Write Message")
            .form-group.col-md-12
              button.btn.btn-default.submit_btn type="submit"  Send Message
          #success
            p Your text message sent successfully!
          #error
            p Sorry! Message not sent. Something went wrong!!
/! ================End Contact Area =================
/! ================Map Area =================
#mapBox.mapBox.row.m0 data-lat="40.5888008" data-lon="-73.6867803" data-zoom="10"
/! ================End Map Area =================
/! ================End Recent Blog Area =================
footer.footer_area
  .footer_widget_area
    .container
      .row
        .col-md-3
          aside.f_widget.about_widget
            .f_w_title
              h4 ABOUT RedCayenne
            p Lorem ipsum dolor sit amet, consectur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris ut.
            ul
              li
                a href="#"
                  i.fa.fa-facebook
              li
                a href="#"
                  i.fa.fa-twitter
              li
                a href="#"
                  i.fa.fa-google-plus
              li
                a href="#"
                  i.fa.fa-linkedin
        .col-md-3
          aside.f_widget.contact_widget
            .f_w_title
              h4 CONTACT US
            p Have questions, comments or just want to say hello:
            ul
              li
                a href="#"
                  i.fa.fa-envelope
                  | backpiper.com@gmail.com
              li
                a href="#"
                  i.fa.fa-phone
                  | +88 01911 854 378
              li
                a href="#"
                  i.fa.fa-map-marker
                  | 5001 E. Colorado Blvd. Suite 820,
                  br/
                  | Pasadena, CA 91106
        .col-md-3
          aside.f_widget.twitter_widget
            .f_w_title
              h4 Twitter Feed
            ul
              li
                a href="#"  @_sumonrahman:
                | Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat.
              li
                a href="#"  @_sumonrahman:
                | Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat.
        .col-md-3
          aside.f_widget.gallery_widget
            .f_w_title
              h4 Gallery On Flickr
            ul
              li
                a href="#"
                  img alt="" src="img/gallery/f-w-gallery/f-w-gallery-1.jpg" /
                  i.fa.fa-search
              li
                a href="#"
                  img alt="" src="img/gallery/f-w-gallery/f-w-gallery-2.jpg" /
                  i.fa.fa-search
              li
                a href="#"
                  img alt="" src="img/gallery/f-w-gallery/f-w-gallery-3.jpg" /
                  i.fa.fa-search
              li
                a href="#"
                  img alt="" src="img/gallery/f-w-gallery/f-w-gallery-4.jpg" /
                  i.fa.fa-search
              li
                a href="#"
                  img alt="" src="img/gallery/f-w-gallery/f-w-gallery-5.jpg" /
                  i.fa.fa-search
              li
                a href="#"
                  img alt="" src="img/gallery/f-w-gallery/f-w-gallery-6.jpg" /
                  i.fa.fa-search
  .copy_right_area
    .container
      .pull-left
        h5
        p
          /! Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0.
          | Copyright ©
          javascript:
            document.write(new Date().getFullYear());
          | All rights reserved | This template is made with
          i.fa.fa-heart-o aria-hidden="true"
          | by
          a href="https://colorlib.com" target="_blank"  Colorlib
          /! Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0.
      .pull-right
        ul.nav.navbar-nav.navbar-right
          li
            a href="#"  Home
          li.active
            a href="#"  About Us
          li
            a href="#"  Menu
          li
            a href="#"  Gallery
          li
            a href="#"  Reservation
          li
            a href="#"  News
          li
            a href="#"  Contact Us
/! ================End Recent Blog Area =================
/! jQuery (necessary for Bootstrap's JavaScript plugins)
script src="js/jquery-2.1.4.min.js"
/! Include all compiled plugins (below), or include individual files as needed
script src="js/bootstrap.min.js"
/! Extra plugin js
script src="vendors/bootstrap-selector/bootstrap-select.js"
script src="vendors/bootatrap-date-time/bootstrap-datetimepicker.min.js"
script src="vendors/owl-carousel/owl.carousel.min.js"
script src="vendors/isotope/imagesloaded.pkgd.min.js"
script src="vendors/isotope/isotope.pkgd.min.js"
script src="vendors/countdown/jquery.countdown.js"
script src="vendors/js-calender/zabuto_calendar.min.js"
/! gmaps Js
script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"
script src="js/gmaps.min.js"
/! contact js
script src="js/jquery.form.js"
script src="js/jquery.validate.min.js"
script src="js/contact.js"
script src="js/video_player.js"
script src="js/theme.js"